Fix bug with exception in foreach
fedyafedko/StudyHub-BE pull request #87
Opened 2024-03-05 10:34 UTC by fedyafedko

2024-03-11 16:02 UTC, Podgore requested changes

2024-03-11 16:02 UTC, Podgore commented on StudyHub/StudyHub.Common/Response/StudentResultResponse.cs
Probably make Failed and Success nullable?

2024-03-11 17:08 UTC, fedyafedko commented on StudyHub/StudyHub/Controllers/UsersController.cs
> +        return Ok(result);
What?

2024-03-21 13:10 UTC, Podgore requested changes

2024-03-21 13:10 UTC, Podgore commented on StudyHub/StudyHub/Controllers/UsersController.cs
> +        return result.Success == null ? Ok(result) : NotFound();
if result == null then Ok()

2024-03-23 14:16 UTC, Podgore approved these changes

2024-03-23 14:18 UTC, merged