Implement google oauth sing up
fedyafedko/StudyHub-BE pull request #88
Opened 2024-03-11 19:35 UTC by Podgore

2024-03-13 07:05 UTC, fedyafedko approved these changes

2024-03-20 14:51 UTC, aquaprogit requested changes

2024-03-20 14:51 UTC, aquaprogit commented on StudyHub/StudyHub/Controllers/GoogleAuthController.cs
> +    public async Task<IActionResult> GoogleRegister([FromHeader(Name = "Authorization-Code")] string authorizationCode, string token)
you should pass primitives either in some class or in header/query

2024-03-31 21:16 UTC, aquaprogit approved these changes

2024-03-31 21:22 UTC, merged